### ISSUE TITLE
dyno import does not work 

### ISSUE THREAD

**Issue by aavileli** [mapbox/dyno#112] opened 2015-12-09 07:35 UTC
usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
TypeError: Cannot read property 'length' of undefined
    at validateList (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/param_validator.js:75:31)
    at validateMember (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/param_validator.js:63:21)
    at validateStructure (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/param_validator.js:48:14)
    at validateMember (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/param_validator.js:61:21)
    at validate (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/param_validator.js:9:10)
    at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/event_listeners.js:88:32)
    at Request.callListeners (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/usr/local/lib/node_modules/dyno/node_modules/aws-sdk/lib/config.js:244:7)

first line of json file is as follows
{"AttributeDefinitions":[{"AttributeName":"id","AttributeType":"S"}],"TableName":"AtomicCounter","KeySchema":[{"AttributeName":"id","KeyType":"HASH"}],"ProvisionedThroughput":{"ReadCapacityUnits":10,"WriteCapacityUnits":10},"TableArn":"arn:aws:dynamodb:us-west-1:1111111111:table/AtomicCounter"}

**Comment by rclark** [comment] 2016-02-20 23:52
Duplicate of #96

**Closed by rclark** 2016-02-20 23:52 UTC
